# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven into the container
COPY target/ContactUs-0.0.1-SNAPSHOT.jar /app/ContactUs.jar

# Expose port 8080 to the outside world
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "contactus.jar"]
